# Generated by Django 3.0.3 on 2020-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20200605_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='situation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
