# Generated by Django 3.0.3 on 2020-06-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_status_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patiente',
            name='last_name',
        ),
    ]
