# Generated by Django 3.0.3 on 2020-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_patiente_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiente',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
