# Generated by Django 3.0.3 on 2020-06-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_patiente_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiente',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
