# Generated by Django 3.0.3 on 2020-06-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_patiente_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('cpf', models.PositiveIntegerField()),
                ('senha', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='patiente',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
