# Generated by Django 3.0.3 on 2020-06-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20200606_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiente',
            name='cpf',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patiente',
            name='rg',
            field=models.IntegerField(null=True),
        ),
    ]
