# Generated by Django 3.0.3 on 2020-06-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20200609_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiente',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
