# Generated by Django 3.0.3 on 2020-06-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20200609_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiente',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
