# Generated by Django 3.0.3 on 2020-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_auto_20200609_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiente',
            name='cpf',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patiente',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patiente',
            name='rg',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
